# Generated by Django 4.0 on 2024-04-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('nbPersonnes', models.CharField(max_length=150)),
                ('montant', models.CharField(max_length=150)),
                ('date_enrigistre', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
