# Generated by Django 4.0 on 2024-04-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leapplica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('adresse', models.CharField(max_length=150)),
                ('date_inscrit', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
