# Generated by Django 4.0 on 2024-04-25 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leapplica', '0002_utilisateurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('idgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leapplica.grouptontine')),
                ('idutilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leapplica.utilisateurs')),
            ],
        ),
    ]
